-- DDL
CREATE TABLE `DB_STATUS` (
	`no` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(10) NULL DEFAULT NULL,
	`ip` VARCHAR(200) NULL DEFAULT NULL,
	`regDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`no`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

-- DML
SELECT * FROM DB_STATUS;

INSERT INTO DB_STATUS (name, ip) values ('GD', '192.168.3.254');

